/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.text.DecimalFormat;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import repository.DotGiamGiaRepository;

/**
 *
 * @author LHH05
 */
public class GiamGiaView extends javax.swing.JPanel {
    private final DotGiamGiaRepository dotGiamGiaRepo = new DotGiamGiaRepository();
    private final List<Map<String, Object>> listDotGiamGia = new ArrayList<>();
    private final List<Map<String, Object>> listSPSearch = new ArrayList<>();
    private Integer selectedSanPhamId;
    private Integer selectedDotGiamGiaId;
    private Integer selectedSanPhamIdSearch;
    private final Timer searchTimer;
    private final DecimalFormat df = new DecimalFormat("#,###");
    private boolean isSelectingSP = false;
    
    SpinnerNumberModel SpnModel = new SpinnerNumberModel();
    
    public GiamGiaView() {
        initComponents();
        dcNgayBatDau.getJCalendar().setMinSelectableDate(new Date());
        dcNgayKetThuc.getJCalendar().setMinSelectableDate(new Date());
        
        // Cấu hình ban đầu cho Spinner giá trị
        spnGiaTri1.setModel(new SpinnerNumberModel(1, 0, 100, 1));
        
        // Khởi tạo Timer debounce cho tìm kiếm sản phẩm (300ms)
        searchTimer = new Timer(300, e -> doProductSearch());
        searchTimer.setRepeats(false);

        JTextField editorField = (JTextField) cbbSanPham.getEditor().getEditorComponent();
        editorField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                if (!isSelectingSP) {
                    searchTimer.restart();
                }
            }
        });

        cbbSanPham.addActionListener(e -> {
            if ("comboBoxChanged".equals(e.getActionCommand())) {
                int index = cbbSanPham.getSelectedIndex();
                if (index >= 0 && index < listSPSearch.size()) {
                    isSelectingSP = true;
                    Map<String, Object> sp = listSPSearch.get(index);
                    selectedSanPhamIdSearch = (Integer) sp.get("id");
                    cbbSanPham.getEditor().setItem(sp.get("ten_ao"));
                    cbbSanPham.hidePopup();
                    isSelectingSP = false;
                }
            }
        });

        loadDotGiamGiaTable();
        loadTableSanPhamGiamGia();
        clearDotGiamGiaForm();
        
        // Đăng ký sự kiện với tên gợi nhớ (Giả định bạn sẽ đổi tên biến trong Design)        
        btnLamMoiDot.addActionListener(evt -> {
            clearDotGiamGiaForm();
            loadDotGiamGiaTable();
        });
        
        btnTaoDot.addActionListener(evt -> onCreateDotGiamGia());
        btnXoaDot.addActionListener(evt -> onUpdateDotGiamGia());

        rdbPhanTram.addActionListener(e -> {
            // Nếu chọn "Phần Trăm" thì giới hạn từ 1 đến 100
            spnGiaTri2.setModel(new SpinnerNumberModel(1, 1, 100, 1));
        });

        rdbCoDinh.addActionListener(e -> {
            // Nếu chọn "Cố Định" thì có thể để giới hạn khác, ví dụ từ 1 đến 100_000_000
            spnGiaTri2.setModel(new SpinnerNumberModel(100_000, 1, 100_000_000, 100_000));
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        pnHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnMain = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDotGiam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spnGiaTri1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rdbDotKhaDung = new javax.swing.JRadioButton();
        rdbDotKhongKhaDung = new javax.swing.JRadioButton();
        btnTaoDot = new javax.swing.JButton();
        btnXoaDot = new javax.swing.JButton();
        btnLamMoiDot = new javax.swing.JButton();
        dcNgayBatDau = new com.toedter.calendar.JDateChooser();
        dcNgayKetThuc = new com.toedter.calendar.JDateChooser();
        cbbSanPham = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnThemDot = new javax.swing.JButton();
        btnHuyDot = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDotGiamGia = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSanPhamGiamGia = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMaGiamGia = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rdbPhanTram = new javax.swing.JRadioButton();
        rdbCoDinh = new javax.swing.JRadioButton();
        spnGiaTri2 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        rdbSanPham = new javax.swing.JRadioButton();
        rdbHoaDon = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        rdbMaKhaDung = new javax.swing.JRadioButton();
        rdbMaKhongKhaDung = new javax.swing.JRadioButton();
        btnTaoMa = new javax.swing.JButton();
        btnHuyMa = new javax.swing.JButton();
        btnLamMoiMa = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnHeader.setBackground(new java.awt.Color(74, 144, 226));
        pnHeader.setPreferredSize(new java.awt.Dimension(957, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ GIẢM GIÁ");

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeaderLayout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(343, 343, 343))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(pnHeader, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(245, 247, 250));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 503));

        jLabel3.setText("Tên Đợt Giảm :");

        jLabel4.setText("Giá Trị :");

        jLabel5.setText("Ngày Kết Thúc :");

        jLabel6.setText("Ngày Bắt Đầu :");

        jLabel7.setText("Trạng Thái :");

        buttonGroup1.add(rdbDotKhaDung);
        rdbDotKhaDung.setSelected(true);
        rdbDotKhaDung.setText("Khả Dụng");
        rdbDotKhaDung.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdbDotKhaDung.setPreferredSize(new java.awt.Dimension(113, 21));

        buttonGroup1.add(rdbDotKhongKhaDung);
        rdbDotKhongKhaDung.setText("Không Khả Dụng");

        btnTaoDot.setText("Tạo");

        btnXoaDot.setText("Xoá");

        btnLamMoiDot.setText("Làm Mới");

        cbbSanPham.setEditable(true);

        jLabel2.setText("Sản phẩm:");

        btnThemDot.setText("Thêm đợt giảm giá");
        btnThemDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDotActionPerformed(evt);
            }
        });

        btnHuyDot.setText("Huỷ đợt giảm giá");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDotGiam)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnGiaTri1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(rdbDotKhaDung, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbDotKhongKhaDung))
                    .addComponent(dcNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnTaoDot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaDot, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLamMoiDot, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnThemDot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHuyDot)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenDotGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnGiaTri1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbDotKhaDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbDotKhongKhaDung))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoDot)
                    .addComponent(btnXoaDot)
                    .addComponent(btnLamMoiDot))
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemDot)
                    .addComponent(btnHuyDot))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_START);

        tblDotGiamGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên Đợt Giảm Giá", "Giá Trị ", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Trạng Thái"
            }
        ));
        tblDotGiamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDotGiamGiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDotGiamGia);

        tblSanPhamGiamGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sản phẩm", "Đợt giảm giá được áp dụng", "Giá bán ", "Giá thực tế"
            }
        ));
        jScrollPane3.setViewportView(tblSanPhamGiamGia);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("ĐỢT GIẢM GIÁ", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tblMaGiamGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Giá Trị", "Đang Giảm", "Loại Áp Dụng", "Start Date", "End Date", "Số Lần Dùng", "Trạng Thái"
            }
        ));
        tblMaGiamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMaGiamGiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMaGiamGia);

        jPanel3.setBackground(new java.awt.Color(245, 247, 250));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 503));

        jLabel8.setText("Mã :");

        jLabel9.setText("Giá Trị :");

        jLabel10.setText("Đang Giảm :");

        buttonGroup2.add(rdbPhanTram);
        rdbPhanTram.setSelected(true);
        rdbPhanTram.setText("Phần Trăm");

        buttonGroup2.add(rdbCoDinh);
        rdbCoDinh.setText("Cố Định");

        jLabel11.setText("Loại Áp Dụng :");

        buttonGroup3.add(rdbSanPham);
        rdbSanPham.setText("Sản Phẩm");

        buttonGroup3.add(rdbHoaDon);
        rdbHoaDon.setText("Hóa Đơn");

        jLabel12.setText("Start Date :");

        jLabel13.setText("End Date :");

        jLabel14.setText("Số Lần Dùng :");

        jLabel15.setText("Trạng Thái :");

        buttonGroup4.add(rdbMaKhaDung);
        rdbMaKhaDung.setSelected(true);
        rdbMaKhaDung.setText("Khả Dụng");

        buttonGroup4.add(rdbMaKhongKhaDung);
        rdbMaKhongKhaDung.setText("Không Khả Dụng");

        btnTaoMa.setText("Tạo");

        btnHuyMa.setText("Hủy");

        btnLamMoiMa.setText("Làm Mới");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rdbSanPham)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(rdbMaKhaDung)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                    .addComponent(rdbMaKhongKhaDung))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(btnTaoMa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnHuyMa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnLamMoiMa))
                                .addComponent(txtMa)
                                .addComponent(spnGiaTri2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(rdbPhanTram)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rdbHoaDon)
                                        .addComponent(rdbCoDinh))
                                    .addGap(19, 19, 19))))))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(spnGiaTri2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbPhanTram)
                    .addComponent(rdbCoDinh))
                .addGap(6, 6, 6)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbSanPham)
                    .addComponent(rdbHoaDon))
                .addGap(6, 6, 6)
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel13)
                .addGap(6, 6, 6)
                .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel15)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbMaKhaDung)
                    .addComponent(rdbMaKhongKhaDung))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoMa)
                    .addComponent(btnHuyMa)
                    .addComponent(btnLamMoiMa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("MÃ GIẢM GIÁ", jPanel2);

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblDotGiamGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDotGiamGiaMouseClicked
        int row = tblDotGiamGia.getSelectedRow();
        if (row < 0 || row >= listDotGiamGia.size()) {
            return;
        }

        Map<String, Object> data = listDotGiamGia.get(row);
        selectedDotGiamGiaId = (Integer) data.get("dotGiamId");
        // Lưu ý: selectedSanPhamId sẽ không còn quan trọng nếu bạn áp dụng cho nhiều SP
        
        txtTenDotGiam.setText(data.get("tenDot") != null ? (String) data.get("tenDot") : "");
        Integer giaTriValue = (Integer) data.get("giaTri");
        spnGiaTri1.setValue(giaTriValue != null ? giaTriValue : 1);
        dcNgayBatDau.setDate((Date) data.get("ngayBatDau"));
        dcNgayKetThuc.setDate((Date) data.get("ngayKetThuc"));
        Boolean tt = (Boolean) data.get("trangThai");
        if (Boolean.TRUE.equals(tt)) {
            rdbDotKhaDung.setSelected(true);
        } else {
            rdbDotKhongKhaDung.setSelected(true);
        }
    }//GEN-LAST:event_tblDotGiamGiaMouseClicked

    private void tblMaGiamGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaGiamGiaMouseClicked
        
    }//GEN-LAST:event_tblMaGiamGiaMouseClicked

    private void btnThemDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDotActionPerformed
        if (selectedDotGiamGiaId == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đợt giảm giá từ bảng bên phải!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (selectedSanPhamIdSearch == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần áp dụng giảm giá!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (dotGiamGiaRepo.attachDiscountToProduct(selectedSanPhamIdSearch, selectedDotGiamGiaId)) {
            JOptionPane.showMessageDialog(this, "Áp dụng giảm giá thành công cho sản phẩm.");
            loadTableSanPhamGiamGia();
        } else {
            JOptionPane.showMessageDialog(this, "Thao tác thất bại. Vui lòng kiểm tra lại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemDotActionPerformed

    private void btnHuyDotActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedSanPhamIdSearch == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần huỷ đợt giảm giá!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn huỷ áp dụng giảm giá cho sản phẩm này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (dotGiamGiaRepo.detachDiscountFromProduct(selectedSanPhamIdSearch)) {
                JOptionPane.showMessageDialog(this, "Đã huỷ áp dụng giảm giá.");
                loadTableSanPhamGiamGia();
            } else {
                JOptionPane.showMessageDialog(this, "Thao tác thất bại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void doProductSearch() {
        JTextField editor = (JTextField) cbbSanPham.getEditor().getEditorComponent();
        String keyword = editor.getText().trim();

        if (keyword.isEmpty()) {
            cbbSanPham.hidePopup();
            listSPSearch.clear();
            selectedSanPhamIdSearch = null;
            return;
        }

        listSPSearch.clear();
        listSPSearch.addAll(dotGiamGiaRepo.searchSanPham(keyword));

        if (listSPSearch.isEmpty()) {
            cbbSanPham.hidePopup();
            selectedSanPhamIdSearch = null;
            return;
        }

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Map<String, Object> sp : listSPSearch) {
            model.addElement((String) sp.get("ten_ao"));
        }

        String currentText = editor.getText();
        int caretPos = editor.getCaretPosition();

        isSelectingSP = true;
        cbbSanPham.setModel(model);
        cbbSanPham.setSelectedIndex(-1);
        editor.setText(currentText);
        if (caretPos <= currentText.length()) {
            editor.setCaretPosition(caretPos);
        }
        isSelectingSP = false;
        cbbSanPham.showPopup();
    }

    private void loadTableSanPhamGiamGia() {
        DefaultTableModel model = (DefaultTableModel) tblSanPhamGiamGia.getModel();
        model.setRowCount(0);
        List<Map<String, Object>> list = dotGiamGiaRepo.getProductsWithDiscounts();
        for (Map<String, Object> item : list) {
            model.addRow(new Object[]{
                item.get("tenSanPham"),
                item.get("tenDot"),
                df.format(item.get("giaBan")),
                df.format(item.get("giaThucTe"))
            });
        }
    }

    private void loadDotGiamGiaTable() {
        DefaultTableModel model = (DefaultTableModel) tblDotGiamGia.getModel();
        model.setRowCount(0);
        listDotGiamGia.clear();
        listDotGiamGia.addAll(dotGiamGiaRepo.getAllWithProductName());

        for (Map<String, Object> rowData : listDotGiamGia) {
            Object trangThai = rowData.get("trangThai");
            String status = "";
            if (rowData.get("dotGiamId") != null) {
                status = "Không Khả Dụng";
                if (trangThai instanceof Boolean && (Boolean) trangThai) {
                    status = "Khả Dụng";
                }
            }
            model.addRow(new Object[]{
                rowData.get("tenDot"),
                rowData.get("giaTri"),
                rowData.get("ngayBatDau"),
                rowData.get("ngayKetThuc"),
                status
            });
        }
    }

    private void onUpdateDotGiamGia() {
        if (selectedDotGiamGiaId == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn đợt giảm giá cần sửa từ bảng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String tenDot = txtTenDotGiam.getText().trim();
        Date ngayBatDau = dcNgayBatDau.getDate();
        Date ngayKetThuc = dcNgayKetThuc.getDate();
        int giaTri = (Integer) spnGiaTri1.getValue();
        boolean trangThai = rdbDotKhaDung.isSelected();

        if (tenDot.isEmpty() || ngayBatDau == null || ngayKetThuc == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (dotGiamGiaRepo.updateCampaign(selectedDotGiamGiaId, tenDot, giaTri, 
                new java.sql.Date(ngayBatDau.getTime()), 
                new java.sql.Date(ngayKetThuc.getTime()), trangThai)) {
            JOptionPane.showMessageDialog(this, "Cập nhật đợt giảm giá thành công.");
            loadDotGiamGiaTable();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearDotGiamGiaForm() {
        selectedDotGiamGiaId = null;
        selectedSanPhamId = null;
        txtTenDotGiam.setText("");
        spnGiaTri1.setValue(1);
        dcNgayBatDau.setDate(null);
        dcNgayKetThuc.setDate(null);
        rdbDotKhaDung.setSelected(true);
        tblDotGiamGia.clearSelection();
        selectedSanPhamIdSearch = null;
        isSelectingSP = true;
        cbbSanPham.setSelectedIndex(-1);
        ((JTextField)cbbSanPham.getEditor().getEditorComponent()).setText("");
        isSelectingSP = false;
    }

    private void onCreateDotGiamGia() {
        // 1. Thu thập dữ liệu từ Form
        String tenDot = txtTenDotGiam.getText().trim();
        if (tenDot.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên đợt giảm không được để trống.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Date ngayBatDau = dcNgayBatDau.getDate();
        Date ngayKetThuc = dcNgayKetThuc.getDate();
        if (ngayBatDau == null || ngayKetThuc == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày bắt đầu và ngày kết thúc.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (ngayKetThuc.before(ngayBatDau)) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc phải lớn hơn hoặc bằng ngày bắt đầu.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int giaTri = (Integer) spnGiaTri1.getValue();
        if (giaTri <= 0) {
            JOptionPane.showMessageDialog(this, "Giá trị giảm giá phải lớn hơn 0.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean trangThai = rdbDotKhaDung.isSelected();

        // 2. Gọi Repository để tạo Chiến dịch giảm giá (Campaign)
        // Bạn cần tạo phương thức insertCampaign trong DotGiamGiaRepository trả về ID vừa tạo
        int newDotGiamId = dotGiamGiaRepo.insertCampaign(
                tenDot,
                giaTri,
                new java.sql.Date(ngayBatDau.getTime()),
                new java.sql.Date(ngayKetThuc.getTime()),
                trangThai
        );

        if (newDotGiamId > 0) {
            // 3. Logic áp dụng cho nhiều sản phẩm
            // Sau khi có ID đợt giảm giá, bạn có thể hiện một Dialog chọn danh sách sản phẩm
            // Hoặc nếu bạn đã có một bảng Sản phẩm có Checkbox trên giao diện, hãy duyệt qua nó:
            
            /* 
            for (Integer spId : listSelectedIds) {
                dotGiamGiaRepo.attachDiscountToProduct(spId, newDotGiamId);
            }
            */

            JOptionPane.showMessageDialog(this, "Tạo đợt giảm giá thành công!\nBạn có thể áp dụng đợt này cho nhiều sản phẩm cùng lúc.", 
                    "Thành công", JOptionPane.INFORMATION_MESSAGE);
            
            loadDotGiamGiaTable();
            clearDotGiamGiaForm();
        } else {
            JOptionPane.showMessageDialog(this, "Tạo đợt giảm giá thất bại. Vui lòng thử lại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyDot;
    private javax.swing.JButton btnHuyMa;
    private javax.swing.JButton btnLamMoiDot;
    private javax.swing.JButton btnLamMoiMa;
    private javax.swing.JButton btnTaoDot;
    private javax.swing.JButton btnTaoMa;
    private javax.swing.JButton btnThemDot;
    private javax.swing.JButton btnXoaDot;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cbbSanPham;
    private com.toedter.calendar.JDateChooser dcNgayBatDau;
    private com.toedter.calendar.JDateChooser dcNgayKetThuc;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMain;
    private javax.swing.JRadioButton rdbCoDinh;
    private javax.swing.JRadioButton rdbDotKhaDung;
    private javax.swing.JRadioButton rdbDotKhongKhaDung;
    private javax.swing.JRadioButton rdbHoaDon;
    private javax.swing.JRadioButton rdbMaKhaDung;
    private javax.swing.JRadioButton rdbMaKhongKhaDung;
    private javax.swing.JRadioButton rdbPhanTram;
    private javax.swing.JRadioButton rdbSanPham;
    private javax.swing.JSpinner spnGiaTri1;
    private javax.swing.JSpinner spnGiaTri2;
    private javax.swing.JTable tblDotGiamGia;
    private javax.swing.JTable tblMaGiamGia;
    private javax.swing.JTable tblSanPhamGiamGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTenDotGiam;
    // End of variables declaration//GEN-END:variables
}
